### ISSUE TITLE
Asortyment

### ISSUE THREAD

**Issue by dzwiedziu-nkg** [pk-azu-2015/shop#3]
Parametry operacji WebServices nie zgadzają się z opisem dokumentacji przez co koledzy nie mogą dziś wykonywać ćwiczenia. Np. metoda "dodaj produkt" powinna mieć "kod produktu(long int), nazwa(string), opis(string), cena(BigDecimal)", a ma jakieś "name(String)". Ocena postępów prac na dzisiaj: 2.0 i proszę jak najszybciej to uzupełnić.

**Comment by nyga07** [comment]
poprawione
